### ISSUE TITLE
It doesn't compile on Elixir 0.15.0-dev

### ISSUE THREAD

**Issue by jamesaspinwall** [checkiz/elixir-bson#3]
I tried to compile it changing the elixir version on mix.exs. But I got the error:

== Compilation error on file lib/bson.ex ==
*\* (CompileError) lib/bson.ex:176: function size/1 undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3
    (elixir) src/elixir.erl:158: :elixir.eval_forms/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3
